---
all:
  children:
    fronts:
      hosts:
        front-01:
          ansible_host: 15.237.180.90

        front-02:
          ansible_host: 51.44.8.212

    glpi_app:
      hosts:
        glpi-app:
          ansible_host: 15.237.214.35

    glpi_db:
      hosts:
        glpi-db:
          ansible_host: 10.0.21.140
          ansible_ssh_common_args: >-
            -o ProxyJump=ubuntu@15.237.180.90
            -o IdentitiesOnly=yes

    jenkins:
      hosts:
        front-01:
          ansible_host: 15.237.180.90