---
all:
  children:
    fronts:
      hosts:
        front-01:
          ansible_host: 13.38.71.191

        front-02:
          ansible_host: 13.36.171.185

    glpi_app:
      hosts:
        glpi-app:
          ansible_host: 15.237.110.189

    glpi_db:
      hosts:
        glpi-db:
          ansible_host: 10.0.21.140
          ansible_ssh_common_args: >-
            -o ProxyJump=ubuntu@13.38.71.191
            -o IdentitiesOnly=yes

    jenkins:
      hosts:
        front-01:
          ansible_host: 13.38.71.191